"""
Subtitle detection module for skip logic.

Detects embedded and external subtitles for skip decisions.
"""

import os
import logging
import glob
from typing import List, Optional
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class ExternalSubtitle:
    """Information about an external subtitle file."""

    path: str
    language: str
    is_subgen_generated: bool
    is_lrc: bool


@dataclass
class EmbeddedSubtitle:
    """Information about an embedded subtitle track."""

    index: int
    codec: str
    language: str
    is_default: bool
    title: Optional[str] = None


class SubtitleDetectionError(Exception):
    """Raised when subtitle detection fails."""

    pass


def is_subgen_subtitle(path: str) -> bool:
    """
    Check if subtitle file was generated by subgen.

    Args:
        path: Path to subtitle file

    Returns:
        True if filename contains .subgen.
    """
    basename = os.path.basename(path)
    return ".subgen." in basename


def scan_external_subtitles(file_path: str) -> List[ExternalSubtitle]:
    """
    Scan for external subtitle files for a media file.

    Args:
        file_path: Path to media file

    Returns:
        List of ExternalSubtitle objects found
    """
    base_path = os.path.splitext(file_path)[0]
    directory = os.path.dirname(file_path)
    basename = os.path.basename(base_path)

    subtitles = []

    # Common subtitle patterns
    patterns = [
        f"{basename}.srt",
        f"{basename}.en.srt",
        f"{basename}.eng.srt",
        f"{basename}.lrc",
    ]

    # Also check for language-specific patterns
    for lang in ["en", "eng", "es", "spa", "fr", "fre", "de", "deu"]:
        patterns.extend([f"{basename}.{lang}.srt", f"{basename}.{lang}.lrc"])

    logger.debug(f"Scanning for external subtitles in {directory} with basename {basename}")
    logger.debug(f"Patterns: {patterns}")

    for pattern in patterns:
        matched_files = glob.glob(os.path.join(directory, pattern))
        logger.debug(f"Pattern {pattern} matched: {matched_files}")
        for matched_path in matched_files:
            try:
                # Extract language from filename
                lang = ""
                filename = os.path.basename(matched_path)

                # Remove extensions
                for ext in [".srt", ".lrc"]:
                    if filename.endswith(ext):
                        filename = filename[: -len(ext)]
                        break

                # Extract language code from filename patterns:
                # 1. "test" -> no language
                # 2. "test.en" -> language "en"
                # 3. "test.eng" -> language "eng"
                # 4. "test.subgen.en" -> language "en" (remove "subgen")
                # 5. "test.subgen.eng" -> language "eng" (remove "subgen")
                parts = filename.split(".")

                # Handle subgen filenames
                if "subgen" in parts:
                    parts.remove("subgen")

                # Get last remaining part as language code
                # Parts might be ["test", "en"] -> lang is "en"
                # Parts might be ["test"] -> no language
                if parts:
                    last_part = parts[-1]
                    if len(last_part) in [2, 3]:
                        lang = last_part

                logger.debug(f"File {filename} -> language: {lang}")

                subtitles.append(
                    ExternalSubtitle(
                        path=matched_path,
                        language=lang,
                        is_subgen_generated=is_subgen_subtitle(matched_path),
                        is_lrc=matched_path.endswith(".lrc"),
                    )
                )
            except Exception as e:
                logger.debug(f"Error parsing subtitle {matched_path}: {e}")

    logger.debug(f"Found {len(subtitles)} external subtitles: {[s.path for s in subtitles]}")
    return subtitles


def get_embedded_subtitles(file_path: str) -> List[EmbeddedSubtitle]:
    """
    Get embedded subtitle tracks from media file.

    Args:
        file_path: Path to media file

    Returns:
        List of EmbeddedSubtitle objects

    Raises:
        SubtitleDetectionError: If FFmpeg probe fails
    """
    try:
        import ffmpeg

        probe = ffmpeg.probe(file_path, select_streams="s")
        subtitle_streams = probe.get("streams", [])

        subtitles = []
        for stream in subtitle_streams:
            subtitles.append(
                EmbeddedSubtitle(
                    index=int(stream.get("index", 0)),
                    codec=stream.get("codec_name", "Unknown"),
                    language=stream.get("tags", {}).get("language", "und"),
                    is_default=stream.get("disposition", {}).get("default", 0) == 1,
                    title=stream.get("tags", {}).get("title"),
                )
            )

        return subtitles
    except Exception as e:
        logger.debug(f"Error detecting embedded subtitles in {file_path}: {e}")
        return []


def has_subtitle_language(subtitles: List, language: str) -> bool:
    """
    Check if any subtitle matches the specified language.

    Args:
        subtitles: List of ExternalSubtitle or EmbeddedSubtitle
        language: Language code to match (e.g., "eng", "en")

    Returns:
        True if matching subtitle found
    """
    if not language:
        return False

    # Create list of equivalent language codes
    equivalent_langs = [language.lower()]
    if len(language) >= 3:
        equivalent_langs.append(language[:3].lower())

    for sub in subtitles:
        sub_lang = sub.language.lower()
        if sub_lang in equivalent_langs or (
            len(sub_lang) >= 3 and sub_lang[:3].lower() in equivalent_langs
        ):
            return True

    return False


def is_audio_file(file_path: str) -> bool:
    """
    Check if file is an audio file based on extension.

    Args:
        file_path: Path to file

    Returns:
        True if file has audio extension
    """
    audio_extensions = {".mp3", ".flac", ".m4a", ".wav", ".ogg", ".opus", ".wma", ".aac"}
    _, ext = os.path.splitext(file_path)
    return ext.lower() in audio_extensions


def is_video_file(file_path: str) -> bool:
    """
    Check if file is a video file based on extension.

    Args:
        file_path: Path to file

    Returns:
        True if file has video extension
    """
    video_extensions = {
        ".mkv",
        ".mp4",
        ".avi",
        ".mov",
        ".m4v",
        ".webm",
        ".flv",
        ".wmv",
        ".mpg",
        ".mpeg",
        ".m2ts",
        ".ts",
    }
    _, ext = os.path.splitext(file_path)
    return ext.lower() in video_extensions
