// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transcription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN   HealthCheckResponse_Status = 0
	HealthCheckResponse_HEALTHY   HealthCheckResponse_Status = 1
	HealthCheckResponse_UNHEALTHY HealthCheckResponse_Status = 2
	HealthCheckResponse_STARTING  HealthCheckResponse_Status = 3
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "STARTING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"STARTING":  3,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_transcription_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_transcription_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{8, 0}
}

type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File path or audio content
	//
	// Types that are valid to be assigned to AudioSource:
	//
	//	*TranscribeRequest_FilePath
	//	*TranscribeRequest_AudioContent
	AudioSource isTranscribeRequest_AudioSource `protobuf_oneof:"audio_source"`
	// Task type: "transcribe" or "translate"
	TaskType string `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	// Force language (ISO 639-1 code) or empty for auto-detect
	ForceLanguage string `protobuf:"bytes,4,opt,name=force_language,json=forceLanguage,proto3" json:"force_language,omitempty"`
	// Transcription options
	Options *TranscribeOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	// Metadata for post-processing (optional)
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., plex_item_id, jellyfin_item_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_transcription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudioSource() isTranscribeRequest_AudioSource {
	if x != nil {
		return x.AudioSource
	}
	return nil
}

func (x *TranscribeRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.AudioSource.(*TranscribeRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *TranscribeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.AudioSource.(*TranscribeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

func (x *TranscribeRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TranscribeRequest) GetForceLanguage() string {
	if x != nil {
		return x.ForceLanguage
	}
	return ""
}

func (x *TranscribeRequest) GetOptions() *TranscribeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TranscribeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isTranscribeRequest_AudioSource interface {
	isTranscribeRequest_AudioSource()
}

type TranscribeRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"` // File path on shared storage
}

type TranscribeRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"` // Audio content bytes (for ASR/Bazarr uploads)
}

func (*TranscribeRequest_FilePath) isTranscribeRequest_AudioSource() {}

func (*TranscribeRequest_AudioContent) isTranscribeRequest_AudioSource() {}

type TranscribeOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whisper model: tiny, base, small, medium, large, large-v3
	WhisperModel string `protobuf:"bytes,1,opt,name=whisper_model,json=whisperModel,proto3" json:"whisper_model,omitempty"`
	// CPU threads for transcription
	WhisperThreads int32 `protobuf:"varint,2,opt,name=whisper_threads,json=whisperThreads,proto3" json:"whisper_threads,omitempty"`
	// Word-level highlighting (karaoke style)
	WordLevelHighlight bool `protobuf:"varint,3,opt,name=word_level_highlight,json=wordLevelHighlight,proto3" json:"word_level_highlight,omitempty"`
	// Custom regroup algorithm (stable-ts)
	CustomRegroup string `protobuf:"bytes,4,opt,name=custom_regroup,json=customRegroup,proto3" json:"custom_regroup,omitempty"`
	// Generate LRC for audio files (vs SRT)
	LrcForAudio bool `protobuf:"varint,5,opt,name=lrc_for_audio,json=lrcForAudio,proto3" json:"lrc_for_audio,omitempty"`
	// Custom prompt for model
	CustomPrompt string `protobuf:"bytes,6,opt,name=custom_prompt,json=customPrompt,proto3" json:"custom_prompt,omitempty"`
	// Append "Transcribed by..." footer
	AppendFooter bool `protobuf:"varint,7,opt,name=append_footer,json=appendFooter,proto3" json:"append_footer,omitempty"`
	// Subtitle language name (aa, en, etc.)
	SubtitleLanguageName string `protobuf:"bytes,8,opt,name=subtitle_language_name,json=subtitleLanguageName,proto3" json:"subtitle_language_name,omitempty"`
	// Show model name in subtitle filename
	ShowModelInFilename bool `protobuf:"varint,9,opt,name=show_model_in_filename,json=showModelInFilename,proto3" json:"show_model_in_filename,omitempty"`
	// Show "subgen" in subtitle filename
	ShowSubgenInFilename bool `protobuf:"varint,10,opt,name=show_subgen_in_filename,json=showSubgenInFilename,proto3" json:"show_subgen_in_filename,omitempty"`
	// Advanced Whisper options (STORY_08)
	// Use custom prompt flag
	UsePrompt bool `protobuf:"varint,11,opt,name=use_prompt,json=usePrompt,proto3" json:"use_prompt,omitempty"`
	// Extra Whisper kwargs as JSON-encoded strings
	// Keys: temperature, beam_size, compression_ratio_threshold, etc.
	// Values: JSON-encoded values (e.g., "0.5", "5", "true")
	ExtraKwargs map[string]string `protobuf:"bytes,12,rep,name=extra_kwargs,json=extraKwargs,proto3" json:"extra_kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Device: cpu, cuda, or gpu
	Device string `protobuf:"bytes,13,opt,name=device,proto3" json:"device,omitempty"`
	// Compute type: auto, int8, int8_float16, float16, float32
	ComputeType   string `protobuf:"bytes,14,opt,name=compute_type,json=computeType,proto3" json:"compute_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeOptions) Reset() {
	*x = TranscribeOptions{}
	mi := &file_transcription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeOptions) ProtoMessage() {}

func (x *TranscribeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeOptions.ProtoReflect.Descriptor instead.
func (*TranscribeOptions) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeOptions) GetWhisperModel() string {
	if x != nil {
		return x.WhisperModel
	}
	return ""
}

func (x *TranscribeOptions) GetWhisperThreads() int32 {
	if x != nil {
		return x.WhisperThreads
	}
	return 0
}

func (x *TranscribeOptions) GetWordLevelHighlight() bool {
	if x != nil {
		return x.WordLevelHighlight
	}
	return false
}

func (x *TranscribeOptions) GetCustomRegroup() string {
	if x != nil {
		return x.CustomRegroup
	}
	return ""
}

func (x *TranscribeOptions) GetLrcForAudio() bool {
	if x != nil {
		return x.LrcForAudio
	}
	return false
}

func (x *TranscribeOptions) GetCustomPrompt() string {
	if x != nil {
		return x.CustomPrompt
	}
	return ""
}

func (x *TranscribeOptions) GetAppendFooter() bool {
	if x != nil {
		return x.AppendFooter
	}
	return false
}

func (x *TranscribeOptions) GetSubtitleLanguageName() string {
	if x != nil {
		return x.SubtitleLanguageName
	}
	return ""
}

func (x *TranscribeOptions) GetShowModelInFilename() bool {
	if x != nil {
		return x.ShowModelInFilename
	}
	return false
}

func (x *TranscribeOptions) GetShowSubgenInFilename() bool {
	if x != nil {
		return x.ShowSubgenInFilename
	}
	return false
}

func (x *TranscribeOptions) GetUsePrompt() bool {
	if x != nil {
		return x.UsePrompt
	}
	return false
}

func (x *TranscribeOptions) GetExtraKwargs() map[string]string {
	if x != nil {
		return x.ExtraKwargs
	}
	return nil
}

func (x *TranscribeOptions) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *TranscribeOptions) GetComputeType() string {
	if x != nil {
		return x.ComputeType
	}
	return ""
}

type SubtitleSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start time in seconds
	Start float32 `protobuf:"fixed32,1,opt,name=start,proto3" json:"start,omitempty"`
	// End time in seconds
	End float32 `protobuf:"fixed32,2,opt,name=end,proto3" json:"end,omitempty"`
	// Text content
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleSegment) Reset() {
	*x = SubtitleSegment{}
	mi := &file_transcription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleSegment) ProtoMessage() {}

func (x *SubtitleSegment) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleSegment.ProtoReflect.Descriptor instead.
func (*SubtitleSegment) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{2}
}

func (x *SubtitleSegment) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SubtitleSegment) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SubtitleSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Subtitle file path (where it was written) - for file-based workflows
	SubtitlePath string `protobuf:"bytes,2,opt,name=subtitle_path,json=subtitlePath,proto3" json:"subtitle_path,omitempty"`
	// Detected language (ISO 639-1 code)
	DetectedLanguage string `protobuf:"bytes,3,opt,name=detected_language,json=detectedLanguage,proto3" json:"detected_language,omitempty"`
	// Error message (if success=false)
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Transcription statistics
	Stats *TranscriptionStats `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	// Subtitle segments - for ASR/API responses
	Segments      []*SubtitleSegment `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_transcription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TranscribeResponse) GetSubtitlePath() string {
	if x != nil {
		return x.SubtitlePath
	}
	return ""
}

func (x *TranscribeResponse) GetDetectedLanguage() string {
	if x != nil {
		return x.DetectedLanguage
	}
	return ""
}

func (x *TranscribeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TranscribeResponse) GetStats() *TranscriptionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *TranscribeResponse) GetSegments() []*SubtitleSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type TranscriptionStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total duration in seconds
	DurationSeconds float32 `protobuf:"fixed32,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Number of subtitle segments
	SegmentCount int32 `protobuf:"varint,2,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	// Model load time (milliseconds)
	ModelLoadTimeMs int64 `protobuf:"varint,3,opt,name=model_load_time_ms,json=modelLoadTimeMs,proto3" json:"model_load_time_ms,omitempty"`
	// Transcription time (milliseconds)
	TranscriptionTimeMs int64 `protobuf:"varint,4,opt,name=transcription_time_ms,json=transcriptionTimeMs,proto3" json:"transcription_time_ms,omitempty"`
	// Peak memory usage (MB)
	PeakMemoryMb  int64 `protobuf:"varint,5,opt,name=peak_memory_mb,json=peakMemoryMb,proto3" json:"peak_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionStats) Reset() {
	*x = TranscriptionStats{}
	mi := &file_transcription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionStats) ProtoMessage() {}

func (x *TranscriptionStats) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionStats.ProtoReflect.Descriptor instead.
func (*TranscriptionStats) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{4}
}

func (x *TranscriptionStats) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TranscriptionStats) GetSegmentCount() int32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *TranscriptionStats) GetModelLoadTimeMs() int64 {
	if x != nil {
		return x.ModelLoadTimeMs
	}
	return 0
}

func (x *TranscriptionStats) GetTranscriptionTimeMs() int64 {
	if x != nil {
		return x.TranscriptionTimeMs
	}
	return 0
}

func (x *TranscriptionStats) GetPeakMemoryMb() int64 {
	if x != nil {
		return x.PeakMemoryMb
	}
	return 0
}

type DetectLanguageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File path or audio content
	//
	// Types that are valid to be assigned to AudioSource:
	//
	//	*DetectLanguageRequest_FilePath
	//	*DetectLanguageRequest_AudioContent
	AudioSource isDetectLanguageRequest_AudioSource `protobuf_oneof:"audio_source"`
	// Sample length in seconds
	SampleLength int32 `protobuf:"varint,3,opt,name=sample_length,json=sampleLength,proto3" json:"sample_length,omitempty"`
	// Sample offset in seconds
	SampleOffset  int32 `protobuf:"varint,4,opt,name=sample_offset,json=sampleOffset,proto3" json:"sample_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectLanguageRequest) Reset() {
	*x = DetectLanguageRequest{}
	mi := &file_transcription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectLanguageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectLanguageRequest) ProtoMessage() {}

func (x *DetectLanguageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectLanguageRequest.ProtoReflect.Descriptor instead.
func (*DetectLanguageRequest) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{5}
}

func (x *DetectLanguageRequest) GetAudioSource() isDetectLanguageRequest_AudioSource {
	if x != nil {
		return x.AudioSource
	}
	return nil
}

func (x *DetectLanguageRequest) GetFilePath() string {
	if x != nil {
		if x, ok := x.AudioSource.(*DetectLanguageRequest_FilePath); ok {
			return x.FilePath
		}
	}
	return ""
}

func (x *DetectLanguageRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.AudioSource.(*DetectLanguageRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

func (x *DetectLanguageRequest) GetSampleLength() int32 {
	if x != nil {
		return x.SampleLength
	}
	return 0
}

func (x *DetectLanguageRequest) GetSampleOffset() int32 {
	if x != nil {
		return x.SampleOffset
	}
	return 0
}

type isDetectLanguageRequest_AudioSource interface {
	isDetectLanguageRequest_AudioSource()
}

type DetectLanguageRequest_FilePath struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3,oneof"`
}

type DetectLanguageRequest_AudioContent struct {
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*DetectLanguageRequest_FilePath) isDetectLanguageRequest_AudioSource() {}

func (*DetectLanguageRequest_AudioContent) isDetectLanguageRequest_AudioSource() {}

type DetectLanguageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Detected language code (ISO 639-1)
	LanguageCode string `protobuf:"bytes,2,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	// Language name in English
	LanguageName string `protobuf:"bytes,3,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`
	// Confidence score (0.0 - 1.0)
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Error message (if success=false)
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectLanguageResponse) Reset() {
	*x = DetectLanguageResponse{}
	mi := &file_transcription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectLanguageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectLanguageResponse) ProtoMessage() {}

func (x *DetectLanguageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectLanguageResponse.ProtoReflect.Descriptor instead.
func (*DetectLanguageResponse) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{6}
}

func (x *DetectLanguageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetectLanguageResponse) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *DetectLanguageResponse) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *DetectLanguageResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectLanguageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_transcription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health status
	Status HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=subgen.v1.HealthCheckResponse_Status" json:"status,omitempty"`
	// Current memory usage (MB)
	MemoryMb int64 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// Is Whisper model loaded?
	ModelLoaded bool `protobuf:"varint,3,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	// Total jobs processed since start
	JobsProcessed int32 `protobuf:"varint,4,opt,name=jobs_processed,json=jobsProcessed,proto3" json:"jobs_processed,omitempty"`
	// Jobs currently processing
	JobsActive int32 `protobuf:"varint,5,opt,name=jobs_active,json=jobsActive,proto3" json:"jobs_active,omitempty"`
	// Worker version
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_transcription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_transcription_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *HealthCheckResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetJobsProcessed() int32 {
	if x != nil {
		return x.JobsProcessed
	}
	return 0
}

func (x *HealthCheckResponse) GetJobsActive() int32 {
	if x != nil {
		return x.JobsActive
	}
	return 0
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_transcription_proto protoreflect.FileDescriptor

const file_transcription_proto_rawDesc = "" +
	"\n" +
	"\x13transcription.proto\x12\tsubgen.v1\"\xea\x02\n" +
	"\x11TranscribeRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContent\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12%\n" +
	"\x0eforce_language\x18\x04 \x01(\tR\rforceLanguage\x126\n" +
	"\aoptions\x18\x05 \x01(\v2\x1c.subgen.v1.TranscribeOptionsR\aoptions\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.subgen.v1.TranscribeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\faudio_source\"\xb6\x05\n" +
	"\x11TranscribeOptions\x12#\n" +
	"\rwhisper_model\x18\x01 \x01(\tR\fwhisperModel\x12'\n" +
	"\x0fwhisper_threads\x18\x02 \x01(\x05R\x0ewhisperThreads\x120\n" +
	"\x14word_level_highlight\x18\x03 \x01(\bR\x12wordLevelHighlight\x12%\n" +
	"\x0ecustom_regroup\x18\x04 \x01(\tR\rcustomRegroup\x12\"\n" +
	"\rlrc_for_audio\x18\x05 \x01(\bR\vlrcForAudio\x12#\n" +
	"\rcustom_prompt\x18\x06 \x01(\tR\fcustomPrompt\x12#\n" +
	"\rappend_footer\x18\a \x01(\bR\fappendFooter\x124\n" +
	"\x16subtitle_language_name\x18\b \x01(\tR\x14subtitleLanguageName\x123\n" +
	"\x16show_model_in_filename\x18\t \x01(\bR\x13showModelInFilename\x125\n" +
	"\x17show_subgen_in_filename\x18\n" +
	" \x01(\bR\x14showSubgenInFilename\x12\x1d\n" +
	"\n" +
	"use_prompt\x18\v \x01(\bR\tusePrompt\x12P\n" +
	"\fextra_kwargs\x18\f \x03(\v2-.subgen.v1.TranscribeOptions.ExtraKwargsEntryR\vextraKwargs\x12\x16\n" +
	"\x06device\x18\r \x01(\tR\x06device\x12!\n" +
	"\fcompute_type\x18\x0e \x01(\tR\vcomputeType\x1a>\n" +
	"\x10ExtraKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x0fSubtitleSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x02R\x03end\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x92\x02\n" +
	"\x12TranscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rsubtitle_path\x18\x02 \x01(\tR\fsubtitlePath\x12+\n" +
	"\x11detected_language\x18\x03 \x01(\tR\x10detectedLanguage\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x123\n" +
	"\x05stats\x18\x05 \x01(\v2\x1d.subgen.v1.TranscriptionStatsR\x05stats\x126\n" +
	"\bsegments\x18\x06 \x03(\v2\x1a.subgen.v1.SubtitleSegmentR\bsegments\"\xeb\x01\n" +
	"\x12TranscriptionStats\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x02R\x0fdurationSeconds\x12#\n" +
	"\rsegment_count\x18\x02 \x01(\x05R\fsegmentCount\x12+\n" +
	"\x12model_load_time_ms\x18\x03 \x01(\x03R\x0fmodelLoadTimeMs\x122\n" +
	"\x15transcription_time_ms\x18\x04 \x01(\x03R\x13transcriptionTimeMs\x12$\n" +
	"\x0epeak_memory_mb\x18\x05 \x01(\x03R\fpeakMemoryMb\"\xb7\x01\n" +
	"\x15DetectLanguageRequest\x12\x1d\n" +
	"\tfile_path\x18\x01 \x01(\tH\x00R\bfilePath\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContent\x12#\n" +
	"\rsample_length\x18\x03 \x01(\x05R\fsampleLength\x12#\n" +
	"\rsample_offset\x18\x04 \x01(\x05R\fsampleOffsetB\x0e\n" +
	"\faudio_source\"\xc1\x01\n" +
	"\x16DetectLanguageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rlanguage_code\x18\x02 \x01(\tR\flanguageCode\x12#\n" +
	"\rlanguage_name\x18\x03 \x01(\tR\flanguageName\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12HealthCheckRequest\"\xde\x02\n" +
	"\x13HealthCheckResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.subgen.v1.HealthCheckResponse.StatusR\x06status\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12!\n" +
	"\fmodel_loaded\x18\x03 \x01(\bR\vmodelLoaded\x12%\n" +
	"\x0ejobs_processed\x18\x04 \x01(\x05R\rjobsProcessed\x12\x1f\n" +
	"\vjobs_active\x18\x05 \x01(\x05R\n" +
	"jobsActive\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\"?\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\f\n" +
	"\bSTARTING\x10\x032\x86\x02\n" +
	"\x14TranscriptionService\x12I\n" +
	"\n" +
	"Transcribe\x12\x1c.subgen.v1.TranscribeRequest\x1a\x1d.subgen.v1.TranscribeResponse\x12U\n" +
	"\x0eDetectLanguage\x12 .subgen.v1.DetectLanguageRequest\x1a!.subgen.v1.DetectLanguageResponse\x12L\n" +
	"\vHealthCheck\x12\x1d.subgen.v1.HealthCheckRequest\x1a\x1e.subgen.v1.HealthCheckResponseB2Z-github.com/mccloud/subgen/orchestrator/pkg/pb\x90\x01\x01b\x06proto3"

var (
	file_transcription_proto_rawDescOnce sync.Once
	file_transcription_proto_rawDescData []byte
)

func file_transcription_proto_rawDescGZIP() []byte {
	file_transcription_proto_rawDescOnce.Do(func() {
		file_transcription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcription_proto_rawDesc), len(file_transcription_proto_rawDesc)))
	})
	return file_transcription_proto_rawDescData
}

var file_transcription_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transcription_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_transcription_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: subgen.v1.HealthCheckResponse.Status
	(*TranscribeRequest)(nil),       // 1: subgen.v1.TranscribeRequest
	(*TranscribeOptions)(nil),       // 2: subgen.v1.TranscribeOptions
	(*SubtitleSegment)(nil),         // 3: subgen.v1.SubtitleSegment
	(*TranscribeResponse)(nil),      // 4: subgen.v1.TranscribeResponse
	(*TranscriptionStats)(nil),      // 5: subgen.v1.TranscriptionStats
	(*DetectLanguageRequest)(nil),   // 6: subgen.v1.DetectLanguageRequest
	(*DetectLanguageResponse)(nil),  // 7: subgen.v1.DetectLanguageResponse
	(*HealthCheckRequest)(nil),      // 8: subgen.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 9: subgen.v1.HealthCheckResponse
	nil,                             // 10: subgen.v1.TranscribeRequest.MetadataEntry
	nil,                             // 11: subgen.v1.TranscribeOptions.ExtraKwargsEntry
}
var file_transcription_proto_depIdxs = []int32{
	2,  // 0: subgen.v1.TranscribeRequest.options:type_name -> subgen.v1.TranscribeOptions
	10, // 1: subgen.v1.TranscribeRequest.metadata:type_name -> subgen.v1.TranscribeRequest.MetadataEntry
	11, // 2: subgen.v1.TranscribeOptions.extra_kwargs:type_name -> subgen.v1.TranscribeOptions.ExtraKwargsEntry
	5,  // 3: subgen.v1.TranscribeResponse.stats:type_name -> subgen.v1.TranscriptionStats
	3,  // 4: subgen.v1.TranscribeResponse.segments:type_name -> subgen.v1.SubtitleSegment
	0,  // 5: subgen.v1.HealthCheckResponse.status:type_name -> subgen.v1.HealthCheckResponse.Status
	1,  // 6: subgen.v1.TranscriptionService.Transcribe:input_type -> subgen.v1.TranscribeRequest
	6,  // 7: subgen.v1.TranscriptionService.DetectLanguage:input_type -> subgen.v1.DetectLanguageRequest
	8,  // 8: subgen.v1.TranscriptionService.HealthCheck:input_type -> subgen.v1.HealthCheckRequest
	4,  // 9: subgen.v1.TranscriptionService.Transcribe:output_type -> subgen.v1.TranscribeResponse
	7,  // 10: subgen.v1.TranscriptionService.DetectLanguage:output_type -> subgen.v1.DetectLanguageResponse
	9,  // 11: subgen.v1.TranscriptionService.HealthCheck:output_type -> subgen.v1.HealthCheckResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_transcription_proto_init() }
func file_transcription_proto_init() {
	if File_transcription_proto != nil {
		return
	}
	file_transcription_proto_msgTypes[0].OneofWrappers = []any{
		(*TranscribeRequest_FilePath)(nil),
		(*TranscribeRequest_AudioContent)(nil),
	}
	file_transcription_proto_msgTypes[5].OneofWrappers = []any{
		(*DetectLanguageRequest_FilePath)(nil),
		(*DetectLanguageRequest_AudioContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcription_proto_rawDesc), len(file_transcription_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcription_proto_goTypes,
		DependencyIndexes: file_transcription_proto_depIdxs,
		EnumInfos:         file_transcription_proto_enumTypes,
		MessageInfos:      file_transcription_proto_msgTypes,
	}.Build()
	File_transcription_proto = out.File
	file_transcription_proto_goTypes = nil
	file_transcription_proto_depIdxs = nil
}
