# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import transcription_pb2 as transcription__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

# Patch: Accept 1.60.1 even though generated with 1.78.0
# This is a workaround for the Docker image having 1.60.1
ACCEPTED_VERSIONS = ["1.60.1", "1.78.0"]

try:
    from grpc._utilities import first_version_is_lower

    # Check if version is in accepted list or >= generated version
    if GRPC_VERSION not in ACCEPTED_VERSIONS:
        _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    # If we can't check version comparison, only accept exact matches
    _version_not_supported = GRPC_VERSION not in ACCEPTED_VERSIONS

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in transcription_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION} or one of {ACCEPTED_VERSIONS}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TranscriptionServiceStub(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
            "/subgen.v1.TranscriptionService/Transcribe",
            request_serializer=transcription__pb2.TranscribeRequest.SerializeToString,
            response_deserializer=transcription__pb2.TranscribeResponse.FromString,
            _registered_method=True,
        )
        self.DetectLanguage = channel.unary_unary(
            "/subgen.v1.TranscriptionService/DetectLanguage",
            request_serializer=transcription__pb2.DetectLanguageRequest.SerializeToString,
            response_deserializer=transcription__pb2.DetectLanguageResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/subgen.v1.TranscriptionService/HealthCheck",
            request_serializer=transcription__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=transcription__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class TranscriptionServiceServicer(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    def Transcribe(self, request, context):
        """Transcribe audio to subtitles (SRT or LRC)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DetectLanguage(self, request, context):
        """Detect language from audio sample"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check for orchestrator monitoring"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Transcribe": grpc.unary_unary_rpc_method_handler(
            servicer.Transcribe,
            request_deserializer=transcription__pb2.TranscribeRequest.FromString,
            response_serializer=transcription__pb2.TranscribeResponse.SerializeToString,
        ),
        "DetectLanguage": grpc.unary_unary_rpc_method_handler(
            servicer.DetectLanguage,
            request_deserializer=transcription__pb2.DetectLanguageRequest.FromString,
            response_serializer=transcription__pb2.DetectLanguageResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=transcription__pb2.HealthCheckRequest.FromString,
            response_serializer=transcription__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "subgen.v1.TranscriptionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("subgen.v1.TranscriptionService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    @staticmethod
    def Transcribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subgen.v1.TranscriptionService/Transcribe",
            transcription__pb2.TranscribeRequest.SerializeToString,
            transcription__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DetectLanguage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subgen.v1.TranscriptionService/DetectLanguage",
            transcription__pb2.DetectLanguageRequest.SerializeToString,
            transcription__pb2.DetectLanguageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subgen.v1.TranscriptionService/HealthCheck",
            transcription__pb2.HealthCheckRequest.SerializeToString,
            transcription__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
