# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import transcription_pb2 as transcription__pb2


class TranscriptionServiceStub(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/subgen.v1.TranscriptionService/Transcribe',
                request_serializer=transcription__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=transcription__pb2.TranscribeResponse.FromString,
                )
        self.DetectLanguage = channel.unary_unary(
                '/subgen.v1.TranscriptionService/DetectLanguage',
                request_serializer=transcription__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=transcription__pb2.DetectLanguageResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/subgen.v1.TranscriptionService/HealthCheck',
                request_serializer=transcription__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=transcription__pb2.HealthCheckResponse.FromString,
                )


class TranscriptionServiceServicer(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    def Transcribe(self, request, context):
        """Transcribe audio to subtitles (SRT or LRC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Detect language from audio sample
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for orchestrator monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=transcription__pb2.TranscribeRequest.FromString,
                    response_serializer=transcription__pb2.TranscribeResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=transcription__pb2.DetectLanguageRequest.FromString,
                    response_serializer=transcription__pb2.DetectLanguageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=transcription__pb2.HealthCheckRequest.FromString,
                    response_serializer=transcription__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'subgen.v1.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """============================================================================
    Transcription Service
    ============================================================================

    """

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subgen.v1.TranscriptionService/Transcribe',
            transcription__pb2.TranscribeRequest.SerializeToString,
            transcription__pb2.TranscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subgen.v1.TranscriptionService/DetectLanguage',
            transcription__pb2.DetectLanguageRequest.SerializeToString,
            transcription__pb2.DetectLanguageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/subgen.v1.TranscriptionService/HealthCheck',
            transcription__pb2.HealthCheckRequest.SerializeToString,
            transcription__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
